### ISSUE TITLE
Visual Studio 2017 Build error

### ISSUE THREAD

**Issue by driesvandamme** [Dwrandaz/AutoUpdateComponent#1]
\bin\x64\Debug\AppxManifest.xml : error APPX0501: Validation error. error 80080204: App manifest validation error: Line 54, Column 54, Reason: The Extension element must specify the Executable attribute with the EntryPoint attribute for a web application.

**Comment by mhmd-azeez** [comment]
Hi, can you provide more context? For example what is at line 54 exactly? Posting the full App manifest would help a lot

**Comment by mhmd-azeez** [comment]
Since this issues lacks repro, I am going to close it. Feel free to re-open it when you posted the required information.
