### ISSUE TITLE
Revert back to previous package

### ISSUE THREAD

**Issue by peter-bozovic** [Dwrandaz/AutoUpdateComponent#3]
This is probably feature request, but it would be great if it would be possible to have the option to revert back to previous package version.

Like if the current version 1.3 is too unstable, possibility to pass the parameter to revert back to the 1.2 version ?
From quick look at the docs, in the PackageManager.UpdatePackageAsync the new version must be higher than the previous one, but maybe something like this would be possible with PackageManager.RemovePackageAsync and PackageManager.AddPackageAsync  ?

**Comment by mhmd-azeez** [comment]
Hi @peter-bozovic while this might seen good at first sight, I think it's too risky to remove/add the package again (You lose everything stored in LocalState). Also I am not sure if a package can remove itself. I suggest just releasing a new version in case of an unstable release. This mechanism worked very well for our apps.

**Comment by peter-bozovic** [comment]
Thank you for the quick reply and the great library.

I see that I can provide custom url for CheckForUpdatesAsync
If I kepp separate .appinstaller file for each version, maybe it is possible to selectively install specific version of the app ?
Like if I have stable 1.2, I can tell only few devices to update to 1.3 and test them before rolling out to 1.3 on all devices.
Just hope I won't have to tweak inside the .appinstaller itself ...

**Comment by mhmd-azeez** [comment]
Indeed you can have multiple update channels by creating multiple folders on your server. For example you call one of the folders `beta` and the other `stable`. And then you configure some of the PCs to check for updates in the `beta` folder and the others in the `stable` folder. When releasing a version, you can first release it to the `beta` folder and everything went smoothly, then release it to the `stable` folder.  I have talked about setting up a multi-channel auto-update mechanism using Azure Blob Storage: https://mazeez.dev/posts/update-sideloaded-uwp-2

While I have used Azure Blob Storage in the blog post, you can use a normal web server too
