### ISSUE TITLE
App crashes after calling await AutoUpdateManager.TryToUpdateAsync(info);

### ISSUE THREAD

**Issue by keytrap-x86** [Dwrandaz/AutoUpdateComponent#4]
Hi,

whenever the code reaches `await AutoUpdateManager.TryToUpdateAsync(info);` the app doesn't restart (the update works)
I have to restart it manually
In the event viewer there is this error 

`
Failed 0x490 while changing the state of the AppModel runtime of the package ______ pour user ______ (actual state=0x00, wanted state=0x20)`

I followed everything in the tutorial.

Min version is set to 1809

**Comment by mhmd-azeez** [comment]
Hi @varKeytrap, unfortunately I no longer have the time or need to maintain this library. Maybe #2 has some information that can help you? 

I have never encoutered this error myself. So I am not sure what's causing the problem. Please make sure that manually updating the app works (by going to the update link and clicking on "install" and then clicking on "update" in the installation wizard). There might be some problem with the package?

Here are a few links that might be helpful for you
 - https://answers.microsoft.com/en-us/windows/forum/windows_10-performance-winpc/failed-with-0x490-modifying-appmodel-runtime/645417d9-94f4-4f43-9e71-6f9c60bbbc7f
 - https://answers.microsoft.com/en-us/windows/forum/windows_10-performance-winpc/failed-with-0x490-modifying-appmodel-runtime/645417d9-94f4-4f43-9e71-6f9c60bbbc7f
 - https://social.technet.microsoft.com/Forums/en-US/565285ce-635d-4570-8b37-72f6905c2823/the-reason-why-error-message-appmodelruntime-69-keep-showing-on-event-viewer?forum=win10itprogeneral

**Comment by keytrap-x86** [comment]
Fixed it by moving the update code from App.cs to MainWindow.cs
